"""Create Nodes Table

Revision ID: 242f91dc05ae
Revises:
Create Date: 2023-04-21 08:47:13.216912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "242f91dc05ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("affiliation", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("support_contact", sa.Text(), nullable=False),
        sa.Column("deployed_since", sa.DateTime(), nullable=False),
        sa.Column("data", sa.Boolean(), nullable=False),
        sa.Column("compute", sa.Boolean(), nullable=False),
        sa.Column("administrators", sa.Text(), nullable=True),
        sa.Column("local", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("local"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nodes")
    # ### end Alembic commands ###
